//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillingRoom
    {
        public int ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string InRoom { get; set; }
        public string InBathroom { get; set; }
        public byte[] ImageRoom { get; set; }
    
        public virtual RoomFund RoomFund { get; set; }
    }
}
