//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagerEntities : DbContext
    {
        private static HotelManagerEntities _context;
        public HotelManagerEntities()
            : base("name=HotelManagerEntities")
        {
        }
        public static HotelManagerEntities GetContext()
        {
            if (_context == null)
                _context = new HotelManagerEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalServices> AdditionalServices { get; set; }
        public virtual DbSet<CheckInCheckOut> CheckInCheckOut { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<FillingRoom> FillingRoom { get; set; }
        public virtual DbSet<ProvisionOfServices> ProvisionOfServices { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<RoomFund> RoomFund { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeNumber> TypeNumber { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
