//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvisionOfServices
    {
        public int ID { get; set; }
        public Nullable<int> ServicesID { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> PriceServices { get; set; }
        public Nullable<int> CheckID { get; set; }
    
        public virtual AdditionalServices AdditionalServices { get; set; }
        public virtual CheckInCheckOut CheckInCheckOut { get; set; }
        public virtual Client Client { get; set; }
        public virtual RoomFund RoomFund { get; set; }
    }
}
