//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomFund()
        {
            this.CheckInCheckOut = new HashSet<CheckInCheckOut>();
            this.FillingRoom = new HashSet<FillingRoom>();
            this.ProvisionOfServices = new HashSet<ProvisionOfServices>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public int Floor { get; set; }
        public int NumberSeats { get; set; }
        public bool Status { get; set; }
        public string ActualStatus
        {
            get
            {
                return (Status) ? "Свободен" : "Занят";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInCheckOut> CheckInCheckOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillingRoom> FillingRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvisionOfServices> ProvisionOfServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual TypeNumber TypeNumber { get; set; }
    }
}
